name: Build and Deploy Spring boot app

on:
  push:
    branches: [develop,dev]

jobs:
  build-docker:
    name: Build and deploy spring proyect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -f backend/pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest


  deploy:
    name: Deploy to DonWeb
    needs: build-docker
    runs-on: self-hosted #ubuntu-latest 

    steps:
      - name: Create directory work
        run: mkdir -p backend/app

      - name: Enter to the directory
        run: cd /home/lrpa/backend/app

      - name: Permises docker 
        run: sudo chmod 666 /var/run/docker.sock

      - name: Docker Instance Stop and remove
        run: sudo docker rm -f s12-14-t-java-react

      - name: Docker pull image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest  

      - name: Docker run image
        run: |
          sudo docker run -d \
            --restart always \
            --name s12-14-t-java-react \
            -p9896:9896 \
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest    

      
#docker run -p 3323:3306 --name mysql_trucking --network spring-mysql-network --restart always -v /root/backend/app:/var/lib/mysql -e  MYSQL_DATABASE=db_trucking -e MYSQL_ROOT_PASSWORD=trucking2023  -d  mysql:8.0.33
