name: Build and Deploy Spring boot app

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-docker:
    name: Build and deploy spring proyect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -f backend/pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest


  deploy:
    name: Deploy to DonWeb
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH INTO IBM4 - DEPLOY
        run: |
          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
              cd /home/lrpa/backend/app
              docker rm -f s12-14-t-java-react
              
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest
              docker run -d \
                --restart always \
                --name s12-14-t-java-react \
                -p9896:9896 \
                ${{ secrets.DOCKERHUB_USERNAME }}/spring-trucking:latest
          EOF
      
#docker run -p 3323:3306 --name mysql_trucking --network spring-mysql-network --restart always -v /root/backend/app:/var/lib/mysql -e  MYSQL_DATABASE=db_trucking -e MYSQL_ROOT_PASSWORD=trucking2023  -d  mysql:8.0.33